name: FehlmannDy SAST
on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep with Pro Rules
        run: |
          semgrep scan \
            --config="p/pro" \
            --config="auto" \
            --error \
            --json \
            --output=sast-results.json
